packages:
  - packages/*
  - docs

ignoredBuiltDependencies:
  - wtf_wikipedia

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - bufferutil
  - esbuild
  - prisma
  - sharp
  - skia-canvas
